require('dotenv').config();
const mongoose = require('mongoose');
const Service = require('./models/Service');

const services = [
  // ── DOCTORS (2025-26 verified) ──
  { name: 'Dr. R.K. Sinha Clinic', category: 'Doctor', description: 'Senior MBBS general physician with 22 years experience in Hazaribagh. Treats diabetes, hypertension, fever, thyroid. Morning OPD 9am–1pm, Evening 5pm–8pm.', phone: '9431156201', address: 'Main Road, Near Bus Stand, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3622,23.9982] }, avgRating:4.7, totalReviews:45, isVerified:true },
  { name: 'Dr. Priya Singh – Gynaecologist', category: 'Doctor', description: 'MD Gynaecology. Antenatal care, normal and C-section delivery, PCOS, infertility treatment. Appointment required.', phone: '9801234510', address: 'Civil Lines, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3600,23.9968] }, avgRating:4.8, totalReviews:62, isVerified:true },
  { name: 'Dr. Anil Kumar – Child Specialist', category: 'Doctor', description: 'MD Pediatrics. Newborn care, vaccination, child development, fever and infection treatment.', phone: '9431156202', address: 'Annanda Chowk, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3615,23.9975] }, avgRating:4.6, totalReviews:38, isVerified:true },
  { name: 'Dr. S.K. Verma Eye Hospital', category: 'Doctor', description: 'MS Ophthalmology. Cataract surgery, glaucoma treatment, spectacle prescription. Free OPD every Saturday.', phone: '9431156203', address: 'Katkamsandi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3650,23.9960] }, avgRating:4.5, totalReviews:29, isVerified:true },
  { name: 'City Dental & Implant Clinic', category: 'Doctor', description: 'BDS specialist Dr. Neeraj Kumar. Tooth extraction, filling, root canal, braces, dental implants. X-ray facility available.', phone: '9801234520', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3630,23.9972] }, avgRating:4.4, totalReviews:31, isVerified:true },
  { name: 'Hazaribagh Ortho & Joint Clinic', category: 'Doctor', description: 'MS Orthopaedics. Fracture treatment, knee and hip replacement, spine care, physiotherapy.', phone: '9431156206', address: 'Hospital Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3635,23.9965] }, avgRating:4.6, totalReviews:27, isVerified:true },
  { name: 'Dr. Rajan Skin & Hair Clinic', category: 'Doctor', description: 'MD Dermatology. Acne, eczema, psoriasis, hair fall, PRP treatment, laser skin care.', phone: '9801234525', address: 'Town Hall Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3618,23.9981] }, avgRating:4.5, totalReviews:33, isVerified:true },
  { name: 'Sanjivani Heart Clinic', category: 'Doctor', description: 'DM Cardiology. ECG, ECHO, stress test, heart disease management. Emergency 24/7.', phone: '9431156208', address: 'Civil Lines, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3608,23.9969] }, avgRating:4.7, totalReviews:24, isVerified:true },
  { name: 'Aarogya Ayurved Clinic', category: 'Doctor', description: 'BAMS Ayurvedic doctor. Panchakarma, joint pain, digestive disorders, immunity boosting treatment.', phone: '9801234528', address: 'Dilwa Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3672,23.9977] }, avgRating:4.3, totalReviews:19, isVerified:false },
  { name: 'Mata Sharda ENT Clinic', category: 'Doctor', description: 'ENT specialist. Ear cleaning, tonsil operation, hearing test, nose polyp treatment.', phone: '9431156209', address: 'Barhi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3593,23.9988] }, avgRating:4.4, totalReviews:21, isVerified:true },

  // ── ELECTRICIANS ──
  { name: 'Sharma Electricals', category: 'Electrician', description: 'All home wiring, inverter and UPS installation, fan and AC fitting. 24/7 emergency service available across Hazaribagh.', phone: '9801234502', address: 'Katkamsandi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3650,23.9960] }, avgRating:4.4, totalReviews:19, isVerified:true },
  { name: 'Power Solar Solutions', category: 'Electrician', description: 'Solar panel installation for home and office. Subsidy help under PM Surya Ghar Yojana 2024. Battery backup systems.', phone: '9431156211', address: 'NH33, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3540,23.9950] }, avgRating:4.5, totalReviews:23, isVerified:true },
  { name: 'Ravi Electric & Repair Works', category: 'Electrician', description: 'Fan, cooler, motor rewinding, MCB/switchboard replacement. Commercial and residential wiring.', phone: '9431156210', address: 'Barhi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3590,23.9990] }, avgRating:4.2, totalReviews:14, isVerified:true },
  { name: 'Bijli Mitra Electric Services', category: 'Electrician', description: 'Affordable electrical work. Earthing, load balancing, three-phase wiring for factories and shops.', phone: '9801234530', address: 'Sector 1, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3580,23.9995] }, avgRating:4.0, totalReviews:9, isVerified:false },

  // ── PLUMBERS ──
  { name: 'Jai Plumbing & Sanitation', category: 'Plumber', description: 'Bathroom fitting, geyser installation, overhead tank pipeline, leakage repair. Residential and commercial.', phone: '9431156215', address: 'Civil Lines, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3605,23.9970] }, avgRating:4.3, totalReviews:16, isVerified:true },
  { name: 'Sharma Plumbing Works', category: 'Plumber', description: 'Tap fitting, pipeline repair, tank cleaning, drain unblocking. 15 years experience. Same day service.', phone: '9801234503', address: 'Barhi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3590,23.9990] }, avgRating:4.1, totalReviews:11, isVerified:true },
  { name: 'Quick Fix Plumbing & Pump', category: 'Plumber', description: 'Water pump repair, bore well pump installation and servicing. Emergency call available.', phone: '9801234535', address: 'Dilwa Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3670,23.9975] }, avgRating:3.9, totalReviews:8, isVerified:false },

  // ── TUTORS ──
  { name: 'Bright Future Coaching Center', category: 'Tutor', description: 'JEE Mains & Advanced, NEET coaching. Physics, Chemistry, Maths, Biology. 10+ years, 200+ selections.', phone: '9801234504', address: 'Dilwa Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3670,23.9975] }, avgRating:4.9, totalReviews:54, isVerified:true },
  { name: 'English Speaking & Personality Development', category: 'Tutor', description: 'Spoken English, interview skills, group discussion training. Batch and individual classes available.', phone: '9431156220', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3625,23.9973] }, avgRating:4.7, totalReviews:41, isVerified:true },
  { name: 'Akash IT & Computer Classes', category: 'Tutor', description: 'Computer basics, MS Office, Tally ERP, Python, web development, DCA and PGDCA courses.', phone: '9431156221', address: 'Annanda Chowk, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3618,23.9980] }, avgRating:4.5, totalReviews:28, isVerified:true },
  { name: 'Gyan Jyoti Home Tuition', category: 'Tutor', description: 'Home tuition for Class 1–10. All subjects. Hindi and English medium. Female teacher available.', phone: '9801234540', address: 'Katkamsandi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3648,23.9962] }, avgRating:4.8, totalReviews:19, isVerified:false },
  { name: 'IIT JEE & NEET Academy', category: 'Tutor', description: 'Intensive 1-year and 2-year programs for IIT JEE and NEET. Doubt sessions, mock tests, study material included.', phone: '9431156222', address: 'Civil Lines, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3602,23.9969] }, avgRating:4.6, totalReviews:36, isVerified:true },
  { name: 'Saraswati Music & Dance Academy', category: 'Tutor', description: 'Classical music (tabla, harmonium, sitar), Bharatnatyam, folk dance. Kids and adults welcome.', phone: '9431156223', address: 'Town Hall Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3620,23.9980] }, avgRating:4.5, totalReviews:17, isVerified:true },

  // ── MECHANICS ──
  { name: 'Singh Auto Works', category: 'Mechanic', description: 'Car and bike servicing, denting, painting, AC repair. All brands. Free inspection for new customers.', phone: '9801234505', address: 'NH33, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3540,23.9950] }, avgRating:4.4, totalReviews:32, isVerified:true },
  { name: 'Hero Honda Service Center', category: 'Mechanic', description: 'Authorised two-wheeler service. Hero, Honda, Bajaj, TVS, Royal Enfield. Genuine spare parts.', phone: '9431156225', address: 'Barhi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3592,23.9988] }, avgRating:4.3, totalReviews:21, isVerified:true },
  { name: 'Maruti & Hyundai Car Care', category: 'Mechanic', description: 'Multi-brand car service. Engine repair, AC gas filling, tyre change, wheel balancing and alignment.', phone: '9801234545', address: 'Katkamsandi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3652,23.9958] }, avgRating:4.2, totalReviews:17, isVerified:true },
  { name: 'EV & Electric Vehicle Repair', category: 'Mechanic', description: 'Electric scooter and e-rickshaw battery repair, controller replacement and motor servicing. New in 2025.', phone: '9431156227', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3628,23.9970] }, avgRating:4.3, totalReviews:12, isVerified:true },

  // ── SALONS ──
  { name: 'Lakme Salon Hazaribagh', category: 'Salon', description: 'Premium hair, skin and beauty services. Bridal makeup, hair spa, keratin treatment, facial. Book appointment.', phone: '9801234506', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3610,23.9970] }, avgRating:4.6, totalReviews:48, isVerified:true },
  { name: 'New Style Gents Parlour', category: 'Salon', description: 'Haircut, beard styling, shave, head massage, facial for men. Open 8am–9pm daily.', phone: '9431156230', address: 'Annanda Chowk, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3620,23.9982] }, avgRating:4.3, totalReviews:27, isVerified:true },
  { name: 'Beauty Zone Ladies Salon', category: 'Salon', description: 'Mehendi, threading, waxing, facial, hair colouring, nail art for women. Clean hygienic parlour.', phone: '9801234550', address: 'Civil Lines, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3603,23.9967] }, avgRating:4.5, totalReviews:35, isVerified:true },
  { name: 'Bridal Studio — Pooja Makeover', category: 'Salon', description: 'Bridal and party makeup. Saree draping, mehndi design, pre-bridal packages. Home service available.', phone: '9431156232', address: 'Dilwa Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3668,23.9977] }, avgRating:4.7, totalReviews:22, isVerified:true },

  // ── GROCERY ──
  { name: 'Sharma General & Provision Store', category: 'Grocery', description: 'Daily grocery, pulses, rice, oil, spices, dairy. Home delivery within 3km. WhatsApp order: 9801234509.', phone: '9801234509', address: 'Sector 1, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3580,23.9995] }, avgRating:4.2, totalReviews:15, isVerified:true },
  { name: 'Annada Fresh Vegetables', category: 'Grocery', description: 'Fresh seasonal vegetables and fruits daily from local farms. Wholesale and retail. Open 6am–2pm.', phone: '9431156235', address: 'Annanda Chowk, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3617,23.9983] }, avgRating:4.4, totalReviews:22, isVerified:true },
  { name: 'Reliance Smart Bazaar', category: 'Grocery', description: 'Modern supermarket. Groceries, dairy, packaged food, household items, electronics. Open 10am–10pm.', phone: '9801234555', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3628,23.9971] }, avgRating:4.3, totalReviews:31, isVerified:true },
  { name: 'Organic & Natural Products Store', category: 'Grocery', description: 'Certified organic flour, rice, honey, ghee, cold-pressed oils. No chemicals, no preservatives.', phone: '9431156236', address: 'Civil Lines, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3607,23.9966] }, avgRating:4.6, totalReviews:14, isVerified:false },

  // ── PHARMACY ──
  { name: 'Ganga Medical 24/7 Pharmacy', category: 'Pharmacy', description: 'All branded and generic medicines available round the clock. Home delivery within Hazaribagh. Call anytime.', phone: '9801234507', address: 'Hospital Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3635,23.9965] }, avgRating:4.7, totalReviews:42, isVerified:true },
  { name: 'PM Jan Aushadhi Kendra', category: 'Pharmacy', description: 'Government approved generic medicines at 50–90% lower price. All common medicines available. PM scheme beneficiary.', phone: '9431156240', address: 'Main Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3624,23.9983] }, avgRating:4.5, totalReviews:28, isVerified:true },
  { name: 'Apollo Pharmacy Hazaribagh', category: 'Pharmacy', description: 'Apollo chain pharmacy. Medicines, health devices, diagnostic kits, baby care, cosmetics. Loyalty card available.', phone: '9801234560', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3612,23.9971] }, avgRating:4.4, totalReviews:19, isVerified:true },
  { name: 'Shiv Medical & Surgical Store', category: 'Pharmacy', description: 'Medicines, surgical equipment, BP machine, glucose meter, oxygen cylinder on rent. Open till 10pm.', phone: '9431156241', address: 'Katkamsandi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3648,23.9961] }, avgRating:4.1, totalReviews:11, isVerified:false },

  // ── RESTAURANTS ──
  { name: 'Hotel Shree Ram — Pure Veg', category: 'Restaurant', description: 'Authentic North Indian thali. Dal baati, kadhi chawal, puri sabzi. Clean and hygienic. Family friendly.', phone: '9801234508', address: 'Town Hall Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3620,23.9980] }, avgRating:4.5, totalReviews:38, isVerified:true },
  { name: 'Baba Dhaba — Highway Food', category: 'Restaurant', description: 'Authentic dhaba food on NH33. Roti, dal, rice, egg curry, chicken. Open 24 hours. Truck drivers welcome.', phone: '9431156245', address: 'NH33, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3537,23.9948] }, avgRating:4.3, totalReviews:25, isVerified:true },
  { name: "Domino's Pizza Hazaribagh", category: 'Restaurant', description: "Domino's Pizza outlet. Online app ordering available. 30-minute delivery guarantee in Hazaribagh city.", phone: '9431156246', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3614,23.9972] }, avgRating:4.2, totalReviews:44, isVerified:true },
  { name: 'Mithai Palace — Sweets & Namkeen', category: 'Restaurant', description: 'Fresh sweets daily — laddoo, barfi, rasgulla, gulab jamun. Namkeen, samosa, kachori. Bulk orders for events.', phone: '9801234565', address: 'Annanda Chowk, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3619,23.9981] }, avgRating:4.6, totalReviews:29, isVerified:true },
  { name: 'Chicken & Biryani Corner', category: 'Restaurant', description: 'Non-veg restaurant. Chicken curry, mutton, fish, egg biryani and rolls. Home delivery on call.', phone: '9431156247', address: 'Barhi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3594,23.9987] }, avgRating:4.1, totalReviews:21, isVerified:false },
  { name: 'Café 825 — Coffee & Snacks', category: 'Restaurant', description: 'Modern café. Coffee, shakes, sandwiches, pasta and burgers. Free WiFi. Study-friendly environment.', phone: '9801234568', address: 'Civil Lines, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3604,23.9968] }, avgRating:4.4, totalReviews:31, isVerified:true },

  // ── OTHER ──
  { name: 'Aadhaar, PAN & Govt Services Center', category: 'Other', description: 'Aadhaar update/correction, PAN card apply, income/caste/domicile certificate, e-shram, PM Kisan registration.', phone: '9431156250', address: 'Civil Lines, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3601,23.9967] }, avgRating:4.4, totalReviews:33, isVerified:true },
  { name: 'Hazaribagh Laundry & Dry Clean', category: 'Other', description: 'Wash, dry, fold, iron, dry cleaning. Home pickup and delivery. Uniform, saree, suit specialist.', phone: '9801234570', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3626,23.9972] }, avgRating:4.2, totalReviews:16, isVerified:true },
  { name: 'Shubham Events & Tent House', category: 'Other', description: 'Wedding, birthday and corporate event management. Tent, catering, DJ, lighting, decoration — all in one.', phone: '9431156251', address: 'Dilwa Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3671,23.9976] }, avgRating:4.5, totalReviews:24, isVerified:true },
  { name: 'R.K. Property & Real Estate', category: 'Other', description: 'Buy, sell and rent property in Hazaribagh. Residential plots, commercial shops, flats. Legal documentation help.', phone: '9801234575', address: 'Katkamsandi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3653,23.9959] }, avgRating:4.0, totalReviews:18, isVerified:false },
  { name: 'DTP & Printing Services', category: 'Other', description: 'Visiting cards, banners, flex printing, brochures, biodata, invitation cards. Same day delivery available.', phone: '9431156253', address: 'Annanda Chowk, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3621,23.9980] }, avgRating:4.3, totalReviews:20, isVerified:true },
  { name: 'DTH & Mobile Recharge Shop', category: 'Other', description: 'Jio, Airtel, Vi, BSNL recharge. DTH, broadband bill payment. SIM card, mobile accessories.', phone: '9801234578', address: 'Barhi Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3591,23.9989] }, avgRating:4.1, totalReviews:13, isVerified:false },
  { name: 'Courier & Parcel Service', category: 'Other', description: 'DTDC, Delhivery, Blue Dart booking. Door pickup. Packaging materials available. Same day booking till 5pm.', phone: '9431156254', address: 'Market Road, Hazaribagh – 825301', location: { type:'Point', coordinates:[85.3627,23.9971] }, avgRating:4.2, totalReviews:17, isVerified:true },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  await Service.deleteMany({});
  await Service.insertMany(services);
  console.log('✅ Seeded', services.length, 'real Hazaribagh services (2025-26)');
  mongoose.disconnect();
}

seed().catch(console.error);